/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Data Structures',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'data-structures/index'
      },
      items: [
        'data-structures/array',
        'data-structures/bloom-filter',
        'data-structures/graph',
        'data-structures/hash-table',
        'data-structures/heap',
        'data-structures/linked-list',
        'data-structures/lru-cache',
        'data-structures/priority-queue',
        'data-structures/queue',
        'data-structures/stack',
        'data-structures/string',
        'data-structures/tree',
        'data-structures/trie',
      ]
    },
    {
      type: 'category',
      label: 'Algorithms',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'algorithms/index'
      },
      items: [
        'algorithms/bit-manipulation',
        'algorithms/depth-first-search',
        'algorithms/breadth-first-search',
        'algorithms/dynamic-programming',
        'algorithms/recursion',
        'algorithms/topological-sorting',
        {
          type: 'category',
          label: 'Sorting and Searching',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'algorithms/sorting-and-searching/index'
          },
          items: [
            'algorithms/sorting-and-searching/bucket-sort'
          ]
        },
        {
          type: 'category',
          label: 'Named Algorithms',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'algorithms/named-algorithms/index'
          },
          items: [
            'algorithms/named-algorithms/dijkstra'
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Patterns',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'patterns/index'
      },
      items: [
        'patterns/index-has-a-hash-key',
        'patterns/precomputation',
        'patterns/sliding-window',
        'patterns/sorting-the-array',
        'patterns/traverse-from-right',
        'patterns/traverse-multiple-times',
        'patterns/two-pointers',
        'patterns/counting-characters',
        'patterns/anagram',
        'patterns/palindrome',
      ]
    },
    {
      type: 'category',
      label: 'Topics',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'topics/index'
      },
      items: [
        'topics/math',
        'topics/matrices',
        'topics/intervals',
      ]
    },
    {
      type: 'category',
      label: 'System Design',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'system-design/index'
      },
      items: [
        'system-design/interview-questions'
      ]
    },
    {
      type: 'category',
      label: 'Tips and Tricks',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'tips-and-tricks/index'
      },
      items: [
        {
          type: 'category',
          label: 'Strings',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'tips-and-tricks/strings/index'
          },
          items: [
            'tips-and-tricks/strings/string-of-unique-characters'
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Templates',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'templates/index'
      },
      items: [
        'templates/binary-search'
      ]
    },
    {
      type: 'category',
      label: 'Learning Resources',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'learning-resources/index'
      },
      items: [
        'learning-resources/general-list',
        'learning-resources/curated-list',
      ]
    },
    {
      type: 'category',
      label: 'Books',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Algorithm Design Manual',
          collapsed: true,
          items: [
            'books/algorithm-design-manual/lecture-notes',
            'books/algorithm-design-manual/exercises-and-solutions',
            {
              type: 'category',
              label: 'Book Notes',
              collapsed: true,
              items: [
                'books/algorithm-design-manual/book-notes/introduction-to-algorithm-design',
                'books/algorithm-design-manual/book-notes/algorithm-analysis',
                'books/algorithm-design-manual/book-notes/data-structures',
                'books/algorithm-design-manual/book-notes/sorting',
                'books/algorithm-design-manual/book-notes/divide-and-conquer',
                'books/algorithm-design-manual/book-notes/hashing-and-randomized-algorithms',
                'books/algorithm-design-manual/book-notes/graph-traversal',
                'books/algorithm-design-manual/book-notes/weighted-graph-algorithms',
                'books/algorithm-design-manual/book-notes/combinatorial-search',
                'books/algorithm-design-manual/book-notes/dynamic-programming',
                'books/algorithm-design-manual/book-notes/np-completeness',
                'books/algorithm-design-manual/book-notes/dealing-with-hard-problems',
                'books/algorithm-design-manual/book-notes/how-to-design-algorithms',
              ]
            },
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Course Notes',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Development and Engineering',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'MIT Missing Semester',
              link: {
                type: 'doc',
                id: 'course-notes/development-and-engineering/mit-missing-semester/index'
              },
              items: [
                'course-notes/development-and-engineering/mit-missing-semester/2020',
                'course-notes/development-and-engineering/mit-missing-semester/2019',
              ]
            },
            'course-notes/development-and-engineering/jsnad/jsnad-course-notes',
            'course-notes/development-and-engineering/jsnsd/jsnsd-course-notes',
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Reference Resources',
        description: 'Something kind of wonderful.',
        keywords: ['reference']
      },
      items: [
        {
          type: 'category',
          label: 'CSS',
          link: {
            type: 'doc',
            id: 'reference/css/index'
          },
          items: [
            'reference/css/css-diner',
          ]
        },
        {
          type: 'category',
          label: 'Docusaurus',
          collapsed: false,
          link: {
            type: 'doc',
            id: 'reference/docusaurus/index'
          },
          items: [
            'reference/docusaurus/documentation-notes',
            'reference/docusaurus/cheatsheet',
            'reference/docusaurus/features',
            'reference/docusaurus/katex',
            'reference/docusaurus/templates',
          ]
        },
      ]
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
