/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Data Structures',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'data-structures/index'
      },
      items: [
        'data-structures/array',
        'data-structures/string',
        'data-structures/hash-table',
        'data-structures/stack',
        'data-structures/queue',
        'data-structures/linked-list',
      ]
    },
    {
      type: 'category',
      label: 'Books',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Algorithm Design Manual',
          collapsed: true,
          items: [
            'books/algorithm-design-manual/lecture-notes',
            'books/algorithm-design-manual/exercises-and-solutions',
            {
              type: 'category',
              label: 'Book Notes',
              collapsed: true,
              items: [
                'books/algorithm-design-manual/book-notes/introduction-to-algorithm-design',
                'books/algorithm-design-manual/book-notes/algorithm-analysis',
                'books/algorithm-design-manual/book-notes/data-structures',
                'books/algorithm-design-manual/book-notes/sorting',
                'books/algorithm-design-manual/book-notes/divide-and-conquer',
                'books/algorithm-design-manual/book-notes/hashing-and-randomized-algorithms',
                'books/algorithm-design-manual/book-notes/graph-traversal',
                'books/algorithm-design-manual/book-notes/weighted-graph-algorithms',
                'books/algorithm-design-manual/book-notes/combinatorial-search',
                'books/algorithm-design-manual/book-notes/dynamic-programming',
                'books/algorithm-design-manual/book-notes/np-completeness',
                'books/algorithm-design-manual/book-notes/dealing-with-hard-problems',
                'books/algorithm-design-manual/book-notes/how-to-design-algorithms',
              ]
            },
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Reference Resources',
        description: 'Something kind of wonderful.',
        keywords: ['reference']
      },
      items: [
        {
          type: 'category',
          label: 'CSS',
          link: {
            type: 'doc',
            id: 'reference/css/index'
          },
          items: [
            'reference/css/css-diner',
          ]
        },
        {
          type: 'category',
          label: 'Docusaurus',
          link: {
            type: 'doc',
            id: 'reference/docusaurus/index'
          },
          items: [
            'reference/docusaurus/documentation-notes',
            'reference/docusaurus/cheatsheet',
            'reference/docusaurus/features',
            'reference/docusaurus/katex',
            'reference/docusaurus/templates',
          ]
        },
      ]
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
